# 1. Сборка фронта
FROM node:20 AS build
WORKDIR /app

COPY package*.json .
RUN npm install

COPY . .
RUN npm run build

# 2. Отдаём собранный фронт через nginx + прокси на backend
FROM nginx:1.25

# Кладём собранные статики
COPY --from=build /app/dist /usr/share/nginx/html

# Конфиг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx","-g","daemon off;"]


server {
    listen 80;

    # Статика фронтенда
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Прокси на backend по /api/*
    location /api/ {
        proxy_pass http://backend:8080;
    }
}
